name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: temurin
          java-version: '21'
      - uses: gradle/actions/setup-gradle@ed408507eac070d1f99cc633dbcf757c94c7933a # v4.4.3
      - run: ./gradlew build --no-daemon
      - uses: dorny/test-reporter@dc9a6ca9ae7e39a464e5215f4ed49af1f1a5c06c # v2.1.0
        if: always()
        with:
          name: Tests
          path: '**/build/test-results/**/*.xml'
          reporter: java-junit
